"""
Route inventory.

BR-12 states that authorization is deny-by-default and that an endpoint without a
declared permission requirement is a startup failure. The full mechanism arrives
with the authorization layer in Phase 2; this test establishes the *decision
gate* now, so that no endpoint can be added without someone consciously deciding
how it is protected.

Every mounted route must therefore appear in exactly one of:

* :data:`PUBLIC_ROUTES` — deliberately unauthenticated, with a written reason;
* a route that declares permissions once the authorization dependency exists
  (Phase 2 extends :func:`_declared_permissions` to read it).

Until then, a new route fails this test until it is classified. That is the
intended behaviour: the cost of adding a line here is seconds, and the cost of an
unprotected endpoint is a data breach.
"""

from __future__ import annotations

from collections.abc import Iterator

import pytest

pytestmark = pytest.mark.architecture

#: Routes that are deliberately reachable without authentication, each with the
#: reason it must be. Public by design, not by omission.
PUBLIC_ROUTES: dict[tuple[str, str], str] = {
    (
        "GET",
        "/health",
    ): "Liveness probe. Exposes no tenant data; reports process state and adapter identity.",
    (
        "GET",
        "/ready",
    ): "Readiness probe. Exposes dependency status only; consumed by the orchestrator.",
    ("GET", "/metrics"): "Prometheus scrape target. Restrict at the reverse proxy in production.",
    ("GET", "/openapi.json"): "Machine-readable API contract.",
    ("GET", "/docs"): "Interactive API documentation.",
    ("GET", "/docs/oauth2-redirect"): "Swagger UI OAuth redirect helper, generated by FastAPI.",
    # -- Authentication ------------------------------------------------------
    # These four are reachable without a bearer token because there is no other
    # way to obtain or renew one. They are public by design, not by omission, and
    # each one is written so that it cannot be used to enumerate accounts: login
    # returns an identical error for an unknown address and a wrong password, and
    # the reset request answers the same way whether or not the address exists.
    (
        "POST",
        "/api/v1/auth/login",
    ): "Credential exchange. No token exists before the first successful sign-in.",
    (
        "POST",
        "/api/v1/auth/refresh",
    ): "Token rotation. The refresh token is the credential; it is opaque and names its own tenant.",
    (
        "POST",
        "/api/v1/auth/password-reset",
    ): "Reset request. Response is identical whether or not the address has an account.",
    (
        "POST",
        "/api/v1/auth/password-reset/confirm",
    ): "Reset completion. The single-use token in the body is the credential.",
    (
        "POST",
        "/api/v1/auth/email/verify-request",
    ): "Public and neutral so an invited user without a session can request proof of mailbox ownership.",
    (
        "POST",
        "/api/v1/auth/email/verify-confirm",
    ): "The expiring single-use email code is the credential; no access token is required.",
}


class _Surface:
    """One mounted operation: its resolved path, methods and dependency list."""

    __slots__ = ("dependencies", "include_in_schema", "methods", "path", "route")

    def __init__(
        self,
        path: str,
        methods: frozenset[str],
        dependencies: list,
        include_in_schema: bool,
        route,
    ) -> None:
        self.path = path
        self.methods = methods
        self.dependencies = dependencies
        self.include_in_schema = include_in_schema
        self.route = route


def _iter_api_routes(app) -> Iterator[_Surface]:
    """
    Yield the application's effective HTTP surface.

    FastAPI 0.141 does **not** flatten an included router into ``app.routes``.
    ``include_router`` appends an ``_IncludedRouter`` wrapper whose ``path`` and
    ``methods`` are ``None``; the real routes live behind it. A traversal that
    simply reads ``app.routes`` therefore sees the three top-level documentation
    routes and nothing else, and every "no unprotected endpoint" assertion passes
    vacuously. That failure mode is worse than having no guard at all, because the
    guard's presence is trusted.

    Two facts make a correct traversal possible, and each is verified below rather
    than assumed:

    * an ``_IncludedRouter`` resolves its children through
      ``effective_route_contexts()``, which applies the ``include_router`` prefix
      and yields ``path``/``methods``/``dependencies`` for each operation;
    * a router that is not wrapped (a plain ``APIRouter``) exposes ``.routes``.

    ``effective_route_contexts`` is preferred because it also reports routes
    registered with ``include_in_schema=False``. Those are the routes most worth
    auditing: they are invisible to the OpenAPI schema, so a scan built on
    ``/openapi.json`` alone would never see them.
    """
    seen: set[int] = set()

    def walk(container) -> Iterator[_Surface]:
        for route in getattr(container, "routes", []):
            if id(route) in seen:
                continue
            seen.add(id(route))

            contexts_of = getattr(route, "effective_route_contexts", None)
            if callable(contexts_of):
                for context in contexts_of():
                    methods = frozenset(context.methods or ())
                    if not context.path or not methods:
                        continue
                    yield _Surface(
                        path=context.path,
                        methods=methods,
                        dependencies=list(getattr(context, "dependencies", ()) or ()),
                        include_in_schema=bool(getattr(context, "include_in_schema", True)),
                        route=getattr(context, "original_route", route),
                    )
                continue

            child_routes = getattr(route, "routes", None)
            if child_routes:
                yield from walk(route)
                continue

            path = getattr(route, "path", None)
            methods = getattr(route, "methods", None)
            if not path or not methods:
                continue
            yield _Surface(
                path=path,
                methods=frozenset(methods),
                dependencies=list(getattr(route, "dependencies", ()) or ()),
                include_in_schema=bool(getattr(route, "include_in_schema", True)),
                route=route,
            )

    yield from walk(app)


#: The attribute ``require_permission`` attaches to the dependency it returns, and
#: the attribute the authentication dependencies attach to themselves. Both are
#: read here rather than reached for through a closure, which is opaque to any
#: inspection.
PERMISSION_MARKER = "__ecomind_permissions__"
AUTHENTICATION_MARKER = "__ecomind_requires_authentication__"


def _collect_from_dependant(dependant, found: list[str], requires_auth: list[bool]) -> None:
    """
    Walk a FastAPI dependant tree collecting permissions and authentication.

    The tree is walked rather than read at the top level because a route's
    dependencies are usually declared in its *signature* (``actor: CurrentActor``),
    which FastAPI resolves into a sub-dependant of the route. Reading only the
    route's own ``dependencies`` list would miss every one of them and the gate
    would pass vacuously — the exact failure this module exists to prevent.
    """
    call = getattr(dependant, "call", None)
    if call is not None:
        declared = getattr(call, PERMISSION_MARKER, None)
        if declared:
            found.extend(declared)
        if getattr(call, AUTHENTICATION_MARKER, False):
            requires_auth.append(True)
    for sub in getattr(dependant, "dependencies", ()) or ():
        _collect_from_dependant(sub, found, requires_auth)


def _is_protected(surface: _Surface) -> bool:
    """
    Whether an operation is protected at all.

    Two things count, and they are different guarantees:

    * it **declares permissions** — the caller must hold every listed code;
    * it **requires authentication** — the caller must present a valid bearer
      token, even if no specific permission is needed.

    The second exists because ``/auth/me`` and ``/auth/logout`` are protected by
    authentication alone: there is no permission to declare, and inventing one to
    satisfy this gate would be a fiction. What must never happen is a route that
    is neither — that is the case this function refuses.
    """
    found: list[str] = []
    requires_auth: list[bool] = []
    for dependency in surface.dependencies:
        _collect_from_dependant(dependency, found, requires_auth)
    _collect_from_dependant(getattr(surface.route, "dependant", None), found, requires_auth)
    return bool(found) or bool(requires_auth)


def _declared_permissions(surface: _Surface) -> list[str]:
    """
    Read the permissions an operation declares.

    Both sources are consulted: the router- or route-level ``dependencies`` list,
    and the resolved dependant tree behind the operation. An operation that
    declares nothing returns an empty list, which is only a failure when it also
    requires no authentication (see :func:`_is_protected`).
    """
    found: list[str] = []
    requires_auth: list[bool] = []
    for dependency in surface.dependencies:
        _collect_from_dependant(dependency, found, requires_auth)
    _collect_from_dependant(getattr(surface.route, "dependant", None), found, requires_auth)
    # Deduplicated but order-preserving: the order is the one the author wrote.
    seen: set[str] = set()
    unique: list[str] = []
    for code in found:
        if code not in seen:
            seen.add(code)
            unique.append(code)
    return unique


#: A traversal that silently finds nothing would make every assertion below pass
#: for the wrong reason. The application always mounts at least the three system
#: probes plus the documentation routes, so the floor is set at five: low enough
#: not to need editing as routes are added, high enough to fail loudly if the
#: traversal breaks again on a FastAPI upgrade.
MINIMUM_EXPECTED_ROUTES = 5


@pytest.fixture
def mounted_surface(test_settings) -> list[_Surface]:
    """
    The application's effective HTTP surface.

    ``test_settings`` is requested so the app is built with the same configuration
    the test suite uses elsewhere, rather than with whatever the developer's
    environment happens to contain.
    """
    from app.main import create_app

    app = create_app(test_settings)
    return sorted(_iter_api_routes(app), key=lambda s: (s.path, sorted(s.methods)))


@pytest.fixture
def mounted_routes(mounted_surface: list[_Surface]) -> list[tuple[str, str]]:
    """Every ``(method, path)`` the application mounts."""
    return sorted(
        (method, surface.path)
        for surface in mounted_surface
        for method in surface.methods
        if method not in {"HEAD", "OPTIONS"}
    )


def test_the_traversal_actually_finds_routes(mounted_surface: list[_Surface]) -> None:
    """
    Guard the guard.

    If a FastAPI upgrade changes how included routers are represented, the
    traversal below could return nothing and every other test in this module would
    pass trivially. This test fails first and says why.
    """
    assert len(mounted_surface) >= MINIMUM_EXPECTED_ROUTES, (
        f"route traversal found only {len(mounted_surface)} operations. Either the "
        "application mounts fewer endpoints than expected, or the traversal no "
        "longer understands how this FastAPI version stores included routers. "
        "Check _iter_api_routes before relaxing this assertion."
    )
    # Every operation must carry a concrete path; a None path means the traversal
    # stopped at a router wrapper instead of a route.
    assert all(surface.path.startswith("/") for surface in mounted_surface)


def test_every_route_is_classified(mounted_surface: list[_Surface]) -> None:
    """
    No operation may be added without deciding how it is protected.

    An operation is acceptable only if it is public by written decision, or it
    declares the permissions it requires. Anything else fails.
    """
    unclassified: list[tuple[str, str]] = []

    for surface in mounted_surface:
        for method in sorted(surface.methods):
            if method in {"HEAD", "OPTIONS"}:
                continue
            if (method, surface.path) in PUBLIC_ROUTES:
                continue
            if _is_protected(surface):
                continue
            unclassified.append((method, surface.path))

    assert not unclassified, (
        "These operations are neither public-by-design nor permission-protected:\n  "
        + "\n  ".join(f"{method} {path}" for method, path in unclassified)
        + "\n\nEither add the route to PUBLIC_ROUTES with a written reason, "
        "declare its required permissions, or make it require authentication "
        "(BR-12)."
    )


def test_public_routes_are_actually_mounted(mounted_routes: list[tuple[str, str]]) -> None:
    """
    The allow-list must not accumulate stale entries.

    A listed route that no longer exists means the classification table has
    drifted from reality, and a future reader would trust it.
    """
    mounted = set(mounted_routes)
    stale = sorted(entry for entry in PUBLIC_ROUTES if entry not in mounted)

    assert not stale, f"PUBLIC_ROUTES lists routes that are not mounted: {stale}"


def test_no_duplicate_route_definitions(mounted_routes: list[tuple[str, str]]) -> None:
    """
    Each ``(method, path)`` must be defined once.

    A duplicate is silently shadowed by whichever the router matched first, so
    the second definition is dead code that nevertheless appears live.
    """
    duplicates = sorted(entry for entry in set(mounted_routes) if mounted_routes.count(entry) > 1)

    assert not duplicates, f"duplicate route definitions: {duplicates}"


def test_api_v1_prefix_is_applied() -> None:
    """
    Feature endpoints must be mounted under the versioned prefix.

    An unversioned feature route cannot be changed compatibly later, which is the
    entire reason the prefix exists.
    """
    from app.api.v1 import api_v1_router

    # The router exists and is mounted under the versioned prefix. Phase 2 adds
    # feature routers to it; this asserts the mount point, which is the part that
    # cannot be changed later without breaking clients.
    assert api_v1_router is not None
    assert api_v1_router.prefix in {"", "/"}
