"""
Declarative base and shared model mixins.

Three decisions are encoded here, each recorded in an ADR:

**Naming convention** — constraints get deterministic names derived from the
table and columns. Without it, PostgreSQL invents names, and an Alembic
autogenerated migration cannot reliably drop or alter a constraint it cannot
name.

**UUID primary keys with server-side defaults** — ``gen_random_uuid()`` is
built into PostgreSQL 13+ (verified on 16.2), so ids are generated by the
database. This means an insert through any path — ORM, bulk ``COPY``, or a
psql script during recovery — produces a valid id.

**Optimistic concurrency as an explicit column, not a mapper directive** —
``VersionMixin`` only declares the ``version`` column. The compare-and-swap
predicate is applied by the repository layer, which lets a stale write surface as
a documented ``409 STALE_RESOURCE`` carrying the current version, rather than as
SQLAlchemy's ``StaleDataError`` that would have to be translated with less
context. See ``docs/api/error-catalogue.md``.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import DateTime, ForeignKey, Integer, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

from app.core.time import utc_now

__all__ = [
    "NAMING_CONVENTION",
    "AuditActorMixin",
    "Base",
    "SoftDeleteMixin",
    "TenantScopedMixin",
    "TimestampMixin",
    "UUIDPrimaryKeyMixin",
    "VersionMixin",
]

#: Deterministic constraint naming. See the module docstring.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every EcoMind-AI entity."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def to_dict(self, *, exclude: set[str] | None = None) -> dict[str, Any]:
        """
        Return column values as a plain dictionary.

        Intended for internal use such as audit metadata and tests. It is
        **never** used to serialise an API response: responses are built from
        Pydantic schemas so that a new column cannot be exposed by accident
        (master directive, section 8).
        """
        excluded = exclude or set()
        return {
            column.key: getattr(self, column.key)
            for column in self.__table__.columns
            if column.key not in excluded
        }

    def __repr__(self) -> str:
        """Identify the row by primary key only — never by its contents."""
        identifier = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identifier}>"


class UUIDPrimaryKeyMixin:
    """A UUID primary key defaulted by the database."""

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Globally unique identifier, generated by the database.",
    )


class TimestampMixin:
    """
    ``created_at`` / ``updated_at`` pairs, stored in UTC.

    ``server_default`` uses the database clock so that rows written by any path
    share one consistent time source; ``onupdate`` maintains ``updated_at`` on
    ORM updates. Bulk updates bypass ``onupdate``, which is why the retention and
    aggregation jobs set the column explicitly.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Row creation time (UTC).",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="Last modification time (UTC).",
    )


class TenantScopedMixin:
    """
    A non-null foreign key to the owning tenant.

    This mixin is the schema-level half of tenant isolation; the query-level and
    policy-level halves live in ``TenantScopedRepository`` and the row-level
    security policies. Every table carrying this mixin must also appear in the
    RLS policy list — asserted by ``tests/db/test_rls_coverage.py`` once model
    tables exist.

    ``ondelete="RESTRICT"`` is deliberate: deleting a tenant must not silently
    cascade away operational history. Tenant offboarding is an explicit,
    audited workflow.
    """

    @declared_attr
    def tenant_id(cls) -> Mapped[UUID]:  # noqa: N805 - SQLAlchemy passes the class
        return mapped_column(
            PGUUID(as_uuid=True),
            # Resolved lazily at DDL time, so the tenants table merely has to
            # exist somewhere in Base.metadata.
            ForeignKey("tenants.id", ondelete="RESTRICT"),
            nullable=False,
            index=True,
            doc="Owning tenant. Enforced here, in the repository and by RLS.",
        )


class SoftDeleteMixin:
    """
    ``deleted_at`` marking, used where operational history must be preserved.

    Master directive BR-19: resources with history are soft-deleted; hard
    deletion exists only through the documented retention/erasure workflow and is
    always audited. Every repository read filters ``deleted_at IS NULL`` unless a
    method is explicitly named ``*_including_deleted``.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        index=True,
        doc="Set when the row is soft-deleted; NULL for live rows.",
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    def soft_delete(self, *, at: datetime | None = None) -> None:
        """Mark the row deleted. Idempotent."""
        if self.deleted_at is None:
            self.deleted_at = at or utc_now()

    def restore(self) -> None:
        """Clear the soft-delete mark. Idempotent."""
        self.deleted_at = None


class VersionMixin:
    """
    An incrementing ``version`` column for optimistic concurrency.

    The column alone does not enforce anything: the repository issues
    ``UPDATE ... WHERE id = :id AND version = :expected_version`` and treats a
    zero row count as a conflict, returning ``409 STALE_RESOURCE`` with the
    current version so a client can refetch and retry.
    """

    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default=text("1"),
        doc="Incremented on every update; used for compare-and-swap updates.",
    )


class AuditActorMixin:
    """
    ``created_by`` / ``updated_by`` actor references.

    Actor ids are nullable because rows may legitimately be created by a
    background job or an inbound device rather than a human user; the audit log
    records the actor type separately and is the authoritative trail.
    """

    @declared_attr
    def created_by(cls) -> Mapped[UUID | None]:  # noqa: N805
        return mapped_column(
            PGUUID(as_uuid=True),
            ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
            doc="User who created the row, when a user was involved.",
        )

    @declared_attr
    def updated_by(cls) -> Mapped[UUID | None]:  # noqa: N805
        return mapped_column(
            PGUUID(as_uuid=True),
            ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
            doc="User who last modified the row, when a user was involved.",
        )
