"""
The seeded role to permission matrix (``rbac.md`` §4).

The matrix is *data*, not code paths: authorization always checks a permission
string, so a tenant may clone a system role, rename it, or build an entirely new
one without any change here. What this module provides is the **starting point**
every tenant is provisioned with.

How the matrix is stored, and why it is stored this way
------------------------------------------------------
``rbac.md`` is the source of truth for who may do what, and it is a table. This
module holds that same table as two literal structures -- the permission
*families* the document names, and the *grant mark* for each role and family --
and derives the resolved permission sets from them. An earlier revision spelled
each role's permissions out as a hand-written frozenset; it drifted from the
document in twenty-one places, which is twenty-one silent authorisation
decisions that no test could see. Deriving the sets from one table means there is
exactly one place where a grant can be changed, and
``tests/security/test_authorization_matrix.py`` compares it against the document
row by row, so drift becomes a failing test instead of a security incident.

Three marks exist, mirroring the document's legend:

``FULL``
    every code in the family is granted;
``OWN``
    only the ``.own`` variant is granted -- the actor may act on records they
    are assigned to, not on the tenant's records as a whole;
``NONE``
    nothing in the family is granted.

Two deliberate omissions, called out because they look like mistakes:

* **``models.manage`` is granted to nobody at tenant level.** Promoting a model
  to ACTIVE is a platform action, because a tenant activating an unevaluated
  model would violate the scientific-integrity rules (ADR-0008).
* **``bins.telemetry.ingest`` is granted to no human role at all.** It is
  reachable only through API-key/device authentication, so a compromised user
  session cannot forge telemetry.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from app.authorization.permissions import PERMISSIONS

__all__ = [
    "GRANTS",
    "ROLE_DEFINITIONS",
    "ROLE_PERMISSION_MAP",
    "RoleDefinition",
    "permissions_for_role",
]

#: How much of a permission family a role receives. The values are the
#: document's legend rendered as symbols.
Grant = Literal["FULL", "OWN", "NONE"]


@dataclass(frozen=True, slots=True)
class RoleDefinition:
    """A seeded role: its identity and the permission codes it grants."""

    code: str
    name: str
    description: str
    level: int
    is_default: bool = False
    permissions: frozenset[str] = field(default_factory=frozenset)


FAMILIES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("users.read", ("users.read",)),
    ("users.write", ("users.write",)),
    ("users.delete", ("users.delete",)),
    ("roles.read", ("roles.read",)),
    ("roles.write", ("roles.write",)),
    ("roles.assign", ("roles.assign",)),
    ("roles.assign.elevate", ("roles.assign.elevate",)),
    ("sessions.read / revoke", ("sessions.read", "sessions.revoke")),
    ("apikeys.*", ("apikeys.read", "apikeys.write")),
    ("settings.read", ("settings.read",)),
    ("settings.write", ("settings.write",)),
    ("scoring.configure", ("scoring.configure",)),
    ("emission_factors.read", ("emission_factors.read",)),
    ("emission_factors.write", ("emission_factors.write",)),
    ("taxonomy.write", ("taxonomy.write",)),
    ("bins.read", ("bins.read",)),
    ("bins.write", ("bins.write",)),
    ("bins.delete", ("bins.delete",)),
    ("bins.telemetry.read", ("bins.telemetry.read",)),
    ("bins.telemetry.ingest", ("bins.telemetry.ingest",)),
    ("bins.maintenance.write", ("bins.maintenance.write",)),
    ("alerts.read", ("alerts.read",)),
    ("alerts.acknowledge / resolve", ("alerts.acknowledge", "alerts.resolve")),
    ("scoring.read", ("scoring.read",)),
    ("collections.read", ("collections.read",)),
    ("collections.create", ("collections.create",)),
    ("collections.update", ("collections.update",)),
    ("collections.complete.own", ("collections.complete.own",)),
    ("collections.cancel", ("collections.cancel",)),
    ("collections.schedule.write", ("collections.schedule.write",)),
    ("routes.read", ("routes.read",)),
    ("routes.create / update", ("routes.create", "routes.update")),
    ("routes.optimize", ("routes.optimize",)),
    ("routes.assign / dispatch", ("routes.assign", "routes.dispatch")),
    ("routes.complete.own", ("routes.complete.own",)),
    ("vehicles.read", ("vehicles.read",)),
    ("vehicles.write / delete", ("vehicles.write", "vehicles.delete")),
    ("vehicles.telemetry.read", ("vehicles.telemetry.read",)),
    ("vehicles.maintenance.write", ("vehicles.maintenance.write",)),
    ("drivers.read", ("drivers.read",)),
    ("drivers.write / assignments.write", ("drivers.write", "drivers.assignments.write")),
    ("facilities.read", ("facilities.read",)),
    ("facilities.write / capacity.write", ("facilities.write", "facilities.capacity.write")),
    ("loads.read", ("loads.read",)),
    ("loads.create / update", ("loads.create", "loads.update")),
    ("loads.transfer", ("loads.transfer",)),
    ("loads.composition.write", ("loads.composition.write",)),
    ("recovery.record", ("recovery.record",)),
    ("weighbridge.record", ("weighbridge.record",)),
    ("analytics.read", ("analytics.read",)),
    ("analytics.export", ("analytics.export",)),
    ("forecasts.read", ("forecasts.read",)),
    ("forecasts.execute", ("forecasts.execute",)),
    ("anomalies.read", ("anomalies.read",)),
    ("anomalies.manage", ("anomalies.manage",)),
    ("classification.execute", ("classification.execute",)),
    ("classification.review", ("classification.review",)),
    ("models.read", ("models.read",)),
    ("models.manage", ("models.manage",)),
    ("recommendations.read", ("recommendations.read",)),
    ("recommendations.act", ("recommendations.act",)),
    ("assistant.use", ("assistant.use",)),
    ("reports.read", ("reports.read",)),
    ("reports.generate", ("reports.generate",)),
    ("reports.export", ("reports.export",)),
    ("audit.read", ("audit.read",)),
    ("integrations.read", ("integrations.read",)),
    ("integrations.write", ("integrations.write",)),
    ("files.upload / files.read.own", ("files.upload", "files.read.own")),
    ("data.export", ("data.export",)),
    ("data.import", ("data.import",)),
    ("retention.configure", ("retention.configure",)),
    (
        "platform.*",
        (
            "audit.read.platform",
            "platform.audit.read",
            "platform.break_glass.activate",
            "platform.jobs.manage",
            "platform.maintenance",
            "platform.models.manage",
            "platform.system_settings.write",
            "platform.tenants.read",
            "platform.tenants.write",
        ),
    ),
)

GRANTS: dict[str, tuple[Grant, ...]] = {
    "SUPER_ADMIN": (
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
    ),
    "TENANT_ADMIN": (
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
    ),
    "OPERATIONS_MANAGER": (
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
    ),
    "DISPATCHER": (
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
    ),
    "DRIVER": (
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "OWN",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
    ),
    "FIELD_WORKER": (
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
    ),
    "FACILITY_MANAGER": (
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
    ),
    "ANALYST": (
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
    ),
    "SUSTAINABILITY_MANAGER": (
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
    ),
    "VIEWER": (
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "OWN",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "FULL",
        "NONE",
        "FULL",
        "FULL",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
        "NONE",
    ),
}


# ---------------------------------------------------------------------------
# Derivation
# ---------------------------------------------------------------------------
def _resolve(role_code: str) -> frozenset[str]:
    """
    The permission codes a role grants, expanded from its grant marks.

    ``OWN`` grants the ``.own`` variant of each code in the family. Where a
    family has no ``.own`` variant the mark grants nothing: a mis-set mark must
    not silently widen a role to the full family.
    """
    marks = GRANTS[role_code]
    if len(marks) != len(FAMILIES):  # pragma: no cover - guarded by the test
        raise ValueError(
            f"role {role_code!r} has {len(marks)} grant marks for {len(FAMILIES)} families"
        )
    granted: set[str] = set()
    for (_family, codes), mark in zip(FAMILIES, marks, strict=True):
        if mark == "FULL":
            granted.update(codes)
        elif mark == "OWN":
            # Only the ``.own`` variant, and only where one exists. A family with
            # no ``.own`` variant therefore grants nothing under an ``OWN`` mark:
            # a mis-set mark must not widen a role to the whole family.
            granted.update(f"{code}.own" for code in codes if f"{code}.own" in PERMISSIONS)
    return frozenset(granted)


def _assert_catalogue_is_complete() -> None:
    """
    Fail at import if the matrix references a code the catalogue does not define.

    A typo in this table would otherwise produce a role that silently lacks a
    permission -- which looks exactly like a working restriction until somebody
    tries to use the feature. Catching it at import time turns that into a
    startup failure with the offending name in the message.
    """
    unknown: set[str] = set()
    for _family, codes in FAMILIES:
        unknown.update(code for code in codes if code not in PERMISSIONS)
    if unknown:
        raise ValueError(
            "the role matrix references permission codes that are not in the "
            f"catalogue: {sorted(unknown)}"
        )


#: Role presentation, keyed by role code. Kept apart from the grants so that the
#: matrix above stays a table of marks rather than a mix of prose and data.
_ROLE_METADATA: dict[str, tuple[str, str, int, bool]] = {
    "SUPER_ADMIN": (
        "Platform administrator",
        "EcoMind platform operator. Owns no tenant data and must activate break-glass to read any.",
        100,
        False,
    ),
    "TENANT_ADMIN": (
        "Tenant administrator",
        "Full control of one tenant, including users, roles and settings.",
        90,
        False,
    ),
    "OPERATIONS_MANAGER": (
        "Operations manager",
        "Runs day-to-day collection operations; no user or role management.",
        70,
        False,
    ),
    "DISPATCHER": (
        "Dispatcher",
        "Builds and dispatches routes, assigns crews, works the live board.",
        60,
        False,
    ),
    "DRIVER": (
        "Driver",
        "Sees only their own route and stops, and completes their own collections.",
        40,
        False,
    ),
    "FIELD_WORKER": (
        "Field worker",
        "Collects and records on the ground, including offline capture.",
        30,
        False,
    ),
    "FACILITY_MANAGER": (
        "Facility manager",
        "Operates a facility: intake, processing outcomes and capacity.",
        50,
        False,
    ),
    "ANALYST": (
        "Analyst",
        "Reads and exports operational and environmental data; changes nothing.",
        20,
        False,
    ),
    "SUSTAINABILITY_MANAGER": (
        "Sustainability manager",
        "Owns carbon, recovery and diversion reporting and the emission factors behind them.",
        35,
        False,
    ),
    "VIEWER": (
        "Viewer",
        "Read-only overview of the tenant's operations.",
        10,
        True,
    ),
}

_ROLES: tuple[RoleDefinition, ...] = tuple(
    RoleDefinition(
        code=code,
        name=metadata[0],
        description=metadata[1],
        level=metadata[2],
        is_default=metadata[3],
        permissions=_resolve(code),
    )
    for code, metadata in _ROLE_METADATA.items()
)

#: Every seeded role, by code.
ROLE_DEFINITIONS: dict[str, RoleDefinition] = {role.code: role for role in _ROLES}

#: The resolved permission set of every seeded role, by code.
ROLE_PERMISSION_MAP: dict[str, frozenset[str]] = {role.code: role.permissions for role in _ROLES}


def permissions_for_role(role_code: str) -> frozenset[str]:
    """
    The permission codes ``role_code`` grants.

    An unknown role yields an empty set rather than raising: this is called while
    building an actor, and a stale role code must not turn every request into a
    500. A role that grants nothing denies everything, which fails closed.
    """
    return ROLE_PERMISSION_MAP.get(role_code, frozenset())


_assert_catalogue_is_complete()
