"""api key rotation integrity and machine audit attribution

Revision ID: 600bc6193a23
Revises: ca9642749b58
Create Date: 2026-09-29 14:00:34.940891+00:00

API-key management was not previously exposed. Before upgrading a deployment
with manually provisioned keys, resolve duplicate non-null rotation_of_id values;
the new unique index deliberately fails rather than silently discard history.
Audit attribution is nullable and does not fabricate historical machine actors.
Downgrade archives machine attribution in reserved audit metadata before removing
the new column/indexes. Re-upgrade restores references to matching surviving keys.
RLS stays forced: the data step explicitly iterates tenant contexts and restores
the previous setting. No credential, key row or audit event is deleted.
Ordinary index DDL may block writes; schedule deployment accordingly.

Design notes for the reviewer:

* Tenant-owned tables require a non-null ``tenant_id`` and forced row-level
  security (``docs/security/security-model.md`` §4). TenantScopedMixin adds
  a registry FK; TenantKeyMixin intentionally omits it for shared-scope rows
  such as sessions and audit logs. Do not infer FK locking from a column name.
  ``tests/db/test_rls_coverage.py`` checks the isolation policies, not universal FKs.
* Measured quantities use ``NUMERIC`` via the aliases in ``app.db.types`` —
  never a floating-point type (master directive, sections 7 and 36).
* Indexes are added for query patterns that exist. Composite indexes follow the
  column order of those queries; an index on the wrong column order is not used.
* A destructive change (dropping a column or table holding operational history)
  requires an explicit data-migration step and a documented rollback plan.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '600bc6193a23'
down_revision: str | None = 'ca9642749b58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_api_keys_tenant_created', 'api_keys', ['tenant_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('uq_api_keys_rotation_source', 'api_keys', ['rotation_of_id'], unique=True, postgresql_where=sa.text('rotation_of_id IS NOT NULL'))
    op.add_column('audit_logs', sa.Column('actor_api_key_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_logs_actor_api_key_id'), 'audit_logs', ['actor_api_key_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_logs_actor_api_key_id_api_keys'), 'audit_logs', 'api_keys', ['actor_api_key_id'], ['id'], ondelete='SET NULL')
    # Restore attribution after a schema rollback, without UUID-casting untrusted
    # historical JSON or attaching an actor from another tenant.
    _per_tenant("""
        UPDATE audit_logs AS a SET actor_api_key_id = k.id
        FROM api_keys AS k
        WHERE a.tenant_id = tenant_scope AND k.tenant_id = tenant_scope
          AND a.actor_type = 'API_KEY' AND a.actor_user_id IS NULL
          AND a.metadata ->> '_machine_actor_ref_v1' = k.id::text
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Privileged, explicit evidence-preserving migration, not a runtime mutation.
    _per_tenant("""
        UPDATE audit_logs AS a SET metadata =
          (CASE WHEN jsonb_typeof(a.metadata) = 'object' THEN a.metadata
                ELSE jsonb_build_object('_previous_metadata', a.metadata) END)
          || jsonb_build_object('_machine_actor_ref_v1', a.actor_api_key_id::text)
        WHERE a.tenant_id = tenant_scope AND a.actor_api_key_id IS NOT NULL
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_logs_actor_api_key_id_api_keys'), 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_actor_api_key_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'actor_api_key_id')
    op.drop_index('uq_api_keys_rotation_source', table_name='api_keys', postgresql_where=sa.text('rotation_of_id IS NOT NULL'))
    op.drop_index('ix_api_keys_tenant_created', table_name='api_keys')
    # ### end Alembic commands ###


def _per_tenant(statement: str) -> None:
    # Fixed migration-authored SQL only. Keeping RLS on supports a non-BYPASSRLS
    # migration owner as well as a privileged deployment role.
    op.execute(sa.text("""
        DO $migration$
        DECLARE tenant_scope uuid;
                previous_scope text := current_setting('app.tenant_id', true);
        BEGIN
          FOR tenant_scope IN SELECT id FROM tenants LOOP
            PERFORM set_config('app.tenant_id', tenant_scope::text, true);
    """ + statement + ";" + """
          END LOOP;
          PERFORM set_config('app.tenant_id', coalesce(previous_scope, ''), true);
        END $migration$;
    """))
