"""platform TOTP enrollment and bound second factor proofs

Revision ID: c4195297efc7
Revises: 1eb8da7c2793
Create Date: 2026-09-29 16:08:58.769513+00:00

Downgrade is intentionally guarded: it must not erase active or pending MFA
state and silently turn an enrolled operator into a password-only operator.
Resolve factor custody and application compatibility through a reviewed operational
migration before rollback. The guard preserves/restores tenant context and leaves
forced RLS enabled. Old application code still lacks enforcement: drain platform
mutations during mixed-version rollout or rollback.

Design notes for the reviewer:

* Tenant-owned tables require a non-null ``tenant_id`` and forced row-level
  security (``docs/security/security-model.md`` §4). TenantScopedMixin adds
  a registry FK; TenantKeyMixin intentionally omits it for shared-scope rows
  such as sessions and audit logs. Do not infer FK locking from a column name.
  ``tests/db/test_rls_coverage.py`` checks the isolation policies, not universal FKs.
* Measured quantities use ``NUMERIC`` via the aliases in ``app.db.types`` —
  never a floating-point type (master directive, sections 7 and 36).
* Indexes are added for query patterns that exist. Composite indexes follow the
  column order of those queries; an index on the wrong column order is not used.
* A destructive change (dropping a column or table holding operational history)
  requires an explicit data-migration step and a documented rollback plan.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c4195297efc7'
down_revision: str | None = '1eb8da7c2793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('platform_mfa_factor_id', sa.Uuid(), nullable=True))
    op.add_column('sessions', sa.Column('platform_mfa_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_factor_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('mfa_last_counter', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('mfa_pending_secret_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mfa_pending_session_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('mfa_pending_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Prevent enrollment racing the guard and column removal. Drain the API first;
    # ordinary DDL can block/deadlock with live transactions and should use timeouts.
    op.execute(sa.text("LOCK TABLE users, sessions IN ACCESS EXCLUSIVE MODE"))
    op.execute(sa.text("""
        DO $mfa_guard$
        DECLARE tenant_scope uuid;
                previous_scope text := current_setting('app.tenant_id', true);
        BEGIN
          FOR tenant_scope IN SELECT id FROM tenants LOOP
            PERFORM set_config('app.tenant_id', tenant_scope::text, true);
            IF EXISTS (SELECT 1 FROM users WHERE tenant_id = tenant_scope AND (
                mfa_secret_encrypted IS NOT NULL OR mfa_factor_id IS NOT NULL OR
                mfa_last_counter IS NOT NULL OR mfa_recovery_hashes IS NOT NULL OR
                mfa_pending_secret_encrypted IS NOT NULL OR mfa_pending_session_id IS NOT NULL OR
                mfa_pending_expires_at IS NOT NULL)) THEN
              RAISE EXCEPTION 'MFA state exists; downgrade requires a reviewed factor recovery migration';
            END IF;
            IF EXISTS (SELECT 1 FROM sessions WHERE tenant_id = tenant_scope AND
                (platform_mfa_verified_at IS NOT NULL OR platform_mfa_factor_id IS NOT NULL)) THEN
              RAISE EXCEPTION 'MFA state exists; downgrade requires a reviewed factor recovery migration';
            END IF;
          END LOOP;
          PERFORM set_config('app.tenant_id', coalesce(previous_scope, ''), true);
        END $mfa_guard$;
    """))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_pending_expires_at')
    op.drop_column('users', 'mfa_pending_session_id')
    op.drop_column('users', 'mfa_pending_secret_encrypted')
    op.drop_column('users', 'mfa_recovery_hashes')
    op.drop_column('users', 'mfa_last_counter')
    op.drop_column('users', 'mfa_factor_id')
    op.drop_column('sessions', 'platform_mfa_verified_at')
    op.drop_column('sessions', 'platform_mfa_factor_id')
    # ### end Alembic commands ###
