"""audit cursor and tenant session browsing indexes

Revision ID: ca9642749b58
Revises: 0a396e61910c
Create Date: 2026-09-29 13:36:59.312100+00:00

Non-destructive index-only revision. The audit index adds its stable id tie-breaker;
sessions gain tenant-first reverse-chronological pagination support. Downgrade
restores the original index definition without changing any audit/session rows.
Standard transactional index DDL can block writes while building: schedule an
appropriate maintenance window on populated production databases.

Design notes for the reviewer:

* Tenant-owned tables must carry ``tenant_id`` with a foreign key to
  ``tenants.id`` and acquire a row-level security policy (see
  ``docs/security/security-model.md`` §4). A table without either is a
  cross-tenant disclosure waiting to happen, and
  ``tests/db/test_rls_coverage.py`` fails the build when one is missing.
* Measured quantities use ``NUMERIC`` via the aliases in ``app.db.types`` —
  never a floating-point type (master directive, sections 7 and 36).
* Indexes are added for query patterns that exist. Composite indexes follow the
  column order of those queries; an index on the wrong column order is not used.
* A destructive change (dropping a column or table holding operational history)
  requires an explicit data-migration step and a documented rollback plan.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ca9642749b58'
down_revision: str | None = '0a396e61910c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_tenant_created'), table_name='audit_logs')
    op.create_index('ix_audit_logs_tenant_created', 'audit_logs', ['tenant_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_sessions_tenant_issued', 'sessions', ['tenant_id', sa.literal_column('issued_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_tenant_issued', table_name='sessions')
    op.drop_index('ix_audit_logs_tenant_created', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_tenant_created'), 'audit_logs', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
