"""session bound platform password reauthentication

Revision ID: 1eb8da7c2793
Revises: 600bc6193a23
Create Date: 2026-09-29 15:37:07.813704+00:00

Existing sessions get NULL (no grant). Downgrade discards only short-lived
confirmation timestamps; re-upgrade must not restore authority from audit history.
Audit records remain untouched. Older application code does not enforce the gate:
isolate the platform control plane during application/schema rollback.

Design notes for the reviewer:

* Tenant-owned tables require a non-null ``tenant_id`` and forced row-level
  security (``docs/security/security-model.md`` §4). TenantScopedMixin adds
  a registry FK; TenantKeyMixin intentionally omits it for shared-scope rows
  such as sessions and audit logs. Do not infer FK locking from a column name.
  ``tests/db/test_rls_coverage.py`` checks the isolation policies, not universal FKs.
* Measured quantities use ``NUMERIC`` via the aliases in ``app.db.types`` —
  never a floating-point type (master directive, sections 7 and 36).
* Indexes are added for query patterns that exist. Composite indexes follow the
  column order of those queries; an index on the wrong column order is not used.
* A destructive change (dropping a column or table holding operational history)
  requires an explicit data-migration step and a documented rollback plan.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1eb8da7c2793'
down_revision: str | None = '600bc6193a23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('platform_reauthenticated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'platform_reauthenticated_at')
    # ### end Alembic commands ###
