"""encrypted auth mail outbox and verification credentials

Revision ID: 0a396e61910c
Revises: 43f430493613
Create Date: 2026-09-29 12:58:02.106375+00:00

Rollout: deploy an independent AUTH_MAIL_ENCRYPTION_KEY to API and mail workers.
Run the worker after upgrading; queued payloads are encrypted, short-lived and
cleared on terminal delivery states. Drain pending messages before key rotation.
Rollback: downgrade deletes the outbox and invalidates outstanding verification
codes. Existing identity/operational rows and audit events are retained.

Design notes for the reviewer:

* Tenant-owned tables must carry ``tenant_id`` with a foreign key to
  ``tenants.id`` and acquire a row-level security policy (see
  ``docs/security/security-model.md`` §4). A table without either is a
  cross-tenant disclosure waiting to happen, and
  ``tests/db/test_rls_coverage.py`` fails the build when one is missing.
* Measured quantities use ``NUMERIC`` via the aliases in ``app.db.types`` —
  never a floating-point type (master directive, sections 7 and 36).
* Indexes are added for query patterns that exist. Composite indexes follow the
  column order of those queries; an index on the wrong column order is not used.
* A destructive change (dropping a column or table holding operational history)
  requires an explicit data-migration step and a documented rollback plan.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0a396e61910c'
down_revision: str | None = '43f430493613'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_mail_outbox',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('PASSWORD_RESET', 'EMAIL_VERIFICATION')", name=op.f('ck_auth_mail_outbox_purpose')),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'FAILED', 'CANCELLED')", name=op.f('ck_auth_mail_outbox_status')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_auth_mail_outbox_attempts_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_auth_mail_outbox_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_mail_outbox_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_mail_outbox'))
    )
    op.create_index('ix_auth_mail_due', 'auth_mail_outbox', ['tenant_id', 'status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_auth_mail_outbox_tenant_id'), 'auth_mail_outbox', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('email_verification_token_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # New tenant data receives its own forced RLS policy in this revision.
    from app.db.rls import tenant_isolation_ddl
    for statement in tenant_isolation_ddl("auth_mail_outbox"):
        op.execute(sa.text(statement))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'email_verification_token_hash')
    op.drop_index(op.f('ix_auth_mail_outbox_tenant_id'), table_name='auth_mail_outbox')
    op.drop_index('ix_auth_mail_due', table_name='auth_mail_outbox')
    op.drop_table('auth_mail_outbox')
    # ### end Alembic commands ###
